[workspace]
members = [ "./gen-ptx", "./sparkl3d-kernels-ptx", "./sparkl2d-kernels-ptx" ]
resolver = "2"

[profile.release]
#codegen-units = 1

[patch.crates-io]
nalgebra = { git = "https://github.com/Vollkornaffe/nalgebra.git", rev = "dd44414a8a27224c4a3d6e68d9368e3b3483d9ce" }
